name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ARTIFACTS_PATH: artifacts
      CHECKOUT_PATH: checkout
      
    steps:        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag todo_app:initial
      
    - name: Login to Docker, Build and Push container to registry
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker build --file=Dockerfile -t lilov88/python.todo.app . && docker push lilov88/python.todo.app
